config/routes.rb
Rails.application.routes.draw do
  draw :sidekiq
  draw :admin

  scope "(:locale)", locale: /#{I18n.available_locales.join("|")}/ do
    root 'articles#index'
    devise_for :users
    draw :articles
    draw :api
  end
end

app/controllers/api/v1/articles_controller.rb
class Api::V1::ArticlesController < ApiController
  skip_before_action :authenticate_request, only: %i[index show]

  def index
    render json: ArticlesBlueprint.render(records), status: :ok
  end

  def show
    render json: ArticlesBlueprint.render(
      record,
      view: :with_comments,
      locale: I18n.locale
    ), status: :ok
  end

  def create
    res = Articles::Operations::Create.call(record_params: record_params)
    return render json: ArticlesBlueprint.render(res.data[:record], locale: I18n.locale), status: res.status.to_sym if res.created?

    render json: { error: res.data[:errors] }, status: res.status.to_sym
  end

  def update
    res = Articles::Operations::Update.call(record_params: record_params, record: record)
    return render json: ArticlesBlueprint.render(res.data[:record], locale: I18n.locale), status: res.status.to_sym if res.ok?

    render json: { error: res.data[:errors] }, status: res.status.to_sym
  end

  def destroy
    head Articles::Operations::Destroy.call(record: record).status.to_sym
  end

  private

  def record_params
    params.require(:article).permit!
  end

  def record_class
    Article
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ResourcesController
  skip_before_action :authenticate_user!, only: %i[index show view_modal]
  before_action :set_locale_to_record, only: %i[create update]

  respond_to :js, only: :view_modal

  def index
    @articles = Article.order(:id)
  end

  def show
    @article = record_class.find(params[:id])
    @comments = @article.comments.order(:id)
    @comment = Comment.new
    # UserMailer.welcome_email(current_user).deliver_later if current_user.present?
  end

  def new
    @article = Article.new
  end

  def create
    res = Articles::Operations::Create.call(record_params: record_params)
    if res.created?
      flash[:success] = MessageHelper.created(record_class.name)
      redirect_to articles_path
    else
      flash[:danger] = res.errors
      redirect_to new_article_path
    end
  end

  def edit
    @article = Article.find(params[:id])
  end

  def update
    res = Articles::Operations::Update.call(record: record, record_params: record_params)
    if res.ok?
      flash[:success] = MessageHelper.updated(record_class.name)
      redirect_to articles_path
    else
      flash[:danger] = res.errors
      redirect_to edit_article_path
    end
  end

  def destroy
    res = Articles::Operations::Destroy.call(record: record)
    if res.no_content?
      flash[:success] = MessageHelper.destroyed(record_class.name)
    else
      flash[:danger] = res.error
    end
    redirect_to articles_path
  end

  def view_modal
    @article = Article.find(params[:id])
    respond_to do |format|
      format.js { render partial: 'view_modal_js', article: @article }
    end
  end

  private

  def record_params
    params.require(:article).permit!
  end

  def record_class
    Article
  end

  def set_locale_to_record
    I18n.locale = record_params[:locale]
  end
end

app/views/articles/_comments.html.slim
h3 Comments: #{@article.comments.count}
- @comments.each do |comment|
  p
    .border.rounded.p-3
      = comment.commentable.email
      br
      == comment.content
      - if current_user.present? && current_user == comment.commentable # Edit comment
        button.btn.btn-outline-dark.mr-2 id="EditComment#{comment.id}" type="button" Edit Comment
        = link_to 'Delete', article_comment_path(@article, comment), method: :delete, class: 'btn btn-outline-danger', data: { confirm: 'Are you sure?' }
        = form_with model: [@article, comment], html: { id: "Comment#{comment.id}", style: 'display: none' } do |form|
          = form.label :content, 'Edit comment'
          = form.rich_text_area :content
          = form.submit class: 'btn btn-outline-success mt-2'
          javascript:
            $("#EditComment#{comment.id}").click(function () {
                $("#Comment#{comment.id}").toggle('show');
            });

app/views/articles/_form.html.slim
= form_with model: article, url: form_url, remote: true do |f|
  = f.hidden_field :locale, value: I18n.locale
  = f.label :title
  br
  = f.text_area :title, class: "form-control"
  br
  = f.label :content
  = f.rich_text_area :content
  = f.label :cover_image

  - if article.cover_image.attached?
    br #{image_tag article.cover_image, width: 100  }
  br
  = f.file_field :cover_image
  br
  = f.submit class: 'btn btn-outline-success mt-2'

app/views/articles/_view_modal.html.slim
.modal.fade.bd-example-modal-lg aria-hidden="true" aria-labelledby="exampleModalLongTitle" role="dialog" tabindex="-1" id="view_modal"
  .modal-dialog.modal-lg role="document"
    .modal-content
      .modal-header
        h5#exampleModalLongTitle.modal-title
          = @article.title

        button.close aria-label="Close" data-dismiss="modal" type="button"
          span aria-hidden="true"  ×
      .modal-body
        == @article.content
      .modal-footer
        button.btn.btn-secondary data-dismiss="modal" type="button"  Close
        = link_to 'Show', article_path(@article), class: 'btn btn-primary'

app/views/articles/_view_modal_js.js.erb
$("body").append("<%= escape_javascript(render(partial: "view_modal", article: @article))%>");
$("#view_modal").modal('show');
$('#view_modal').on('hidden.bs.modal', function () {
    $('#view_modal').remove();
});

app/views/articles/edit.html.slim
.card
  .card-body
    h2 Edit Article
    = render 'articles/form', article: @article, form_url: article_path(@article)

app/views/articles/index.html.slim
.album.py-5
  h2
    = t '.name'
  .row
    - @articles.each do |a|
      .col-md-4
        .card.mb-4.box-shadow
          - if a.cover_image.present?
            = image_tag a.cover_image, height: 140, focusable: false, class: "card-img-top"
          - else
            = image_tag 'default_image.png', height: 140, focusable: false, class: "card-img-top"
          .card-body
            p.card-text
              = a.title if a.title.present?
            .d-flex.justify-content-between.align-items-center
              .btn-group
                = link_to t('.show'), article_path(a), class: 'btn btn-sm btn-outline-secondary'
                = link_to t('.view'), view_modal_article_path(a), remote: true, class: 'btn btn-sm btn-outline-secondary'
                = link_to t('.edit'), edit_article_path(a), class: 'btn btn-sm btn-outline-secondary' if current_user.present? && current_user.admin?
              small.text-muted

app/views/articles/new.html.slim
.card
  .card-body
    h1
      = t '.new'
    = render 'articles/form', article: @article, form_url: articles_path(@article)

app/views/articles/show.html.slim
.container
  .card
    .card-body
      h1 Title: #{@article.title}
      = image_tag @article.cover_image, width: 300, class: "bd-placeholder-img rounded" if @article.cover_image.attached?
      h2 Content:
      ==@article.content
      = render 'articles/comments', article: @article, comments: @comments
      - if current_user.present?
        = form_with model: [@article, @comment] do |f|
          = f.label :content, 'Create new comment:'
          = f.rich_text_area :content
          br
          = f.submit class: 'btn btn-outline-success mb-2'
      - else
        p To be able to leave comments you need log in
      = link_to 'Edit Article', edit_article_path(@article), class: 'btn btn-outline-dark mr-2'
      = link_to 'Destroy', article_path(@article), method: :delete, data: { confirm: 'Are you sure?'}, class: 'btn btn-outline-danger'