config/routes.rb
Rails.application.routes.draw do
  draw :sidekiq
  draw :admin

  scope "(:locale)", locale: /#{I18n.available_locales.join("|")}/ do
    root 'articles#index'
    devise_for :users
    draw :articles
    draw :api
  end
end

app/views/shared/_alert.html.slim
.container
  - if notice.present?
    p class="alert alert-primary"
      = notice
  - if alert.present?
    p class="alert alert-dark"
      = alert
  - if flash[:danger].present?
    p class="alert alert-danger"
      - flash[:danger].each do |name, massage|
        | #{name.capitalize}: #{massage.first}
        br
  - if flash[:success].present?
    p class="alert alert-success"
      = flash[:success]
  - if flash[:warning].present?
    p class="alert alert-warning"
      = flash[:warning]

app/views/shared/_navbar.html.slim
nav.navbar.navbar-expand-sm.navbar-dark.bg-dark.mb-3
  .container
    = link_to t('global.menu.name_project'), root_path, class: "navbar-brand"
    .collapse.navbar-collapse
      ul.navbar-nav.mr-auto
        li.nav-item.active
          = link_to 'UK', { locale: :uk }, class: 'nav-link'
        li.nav-item.active
          = link_to 'EN', { locale: :en }, class: 'nav-link'
        li.nav-item.active
          = link_to t('global.menu.administrate'), rails_admin_path, class: "nav-link" if current_user.present? && current_user.admin?
      form.form-inline.my-2.my-md-0
        ul.navbar-nav.mr-auto
          li.nav-item.active
            = link_to t('global.menu.articles'), articles_path, class: "nav-link"
          - if current_user.present?
            li.nav-item.active
              = link_to t('global.menu.create_article'), new_article_path, class: "nav-link" if current_user.admin?
            li.nav-item.active
              = link_to t('global.menu.sing_out'), destroy_user_session_path, method: :delete, class: "btn btn-outline-light"
          - else
            li.nav-item.active
              = link_to t('global.menu.sing_in'), new_user_session_path, class: "btn btn-outline-light"